// export const GF_RPC_URL =
//   'https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org';
//   export const GF_CHAIN_ID = 5600;

const {
  REACT_APP_GF_CHAIN_ID,
  REACT_APP_GF_RPC_URL,
  REACT_APP_BSC_RPC_URL,
  REACT_APP_BSC_CHAIN_ID,

  REACT_APP_MARKETPLACE_CONTRACT_ADDRESS,
  REACT_APP_GROUP_HUB_CONTRACT_ADDRESS,
  REACT_APP_MULTI_CALL_CONTRACT_ADDRESS,
  REACT_APP_CROSS_CHAIN_FEE,
  REACT_APP_INITIATE_LIST_FEE,

  REACT_APP_LIST_FEE_ON_GF,
  REACT_APP_LIST_ESTIMATE_FEE_ON_BSC,
} = process.env;

export const GF_CHAIN_ID = Number(REACT_APP_GF_CHAIN_ID);
export const GF_RPC_URL = REACT_APP_GF_RPC_URL as string;
export const BSC_RPC_URL = REACT_APP_BSC_RPC_URL as string;
export const BSC_CHAIN_ID = Number(REACT_APP_BSC_CHAIN_ID);

export const MARKETPLACE_CONTRACT_ADDRESS =
  REACT_APP_MARKETPLACE_CONTRACT_ADDRESS as string;
export const GROUP_HUB_CONTRACT_ADDRESS =
  REACT_APP_GROUP_HUB_CONTRACT_ADDRESS as string;
export const MULTI_CALL_CONTRACT_ADDRESS =
  REACT_APP_MULTI_CALL_CONTRACT_ADDRESS as string;

export const CROSS_CHAIN_FEE = Number(REACT_APP_CROSS_CHAIN_FEE);
export const INITIATE_LIST_FEE = Number(REACT_APP_INITIATE_LIST_FEE);

export const LIST_FEE_ON_GF = Number(REACT_APP_LIST_FEE_ON_GF);
export const LIST_ESTIMATE_FEE_ON_BSC = Number(
  REACT_APP_LIST_ESTIMATE_FEE_ON_BSC,
);
